png(file="./plot4.png")
library(data.table)
colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric")
DT <- read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings=c("?"),colClasses=colClasses)
DT[[1]] <- as.Date(DT[[1]], "%d/%m/%Y")
good <- (DT[[1]]==as.Date("1/2/2007", "%d/%m/%Y") | DT[[1]]==as.Date("2/2/2007", "%d/%m/%Y"))
d <- DT[good,]
d$Time <- strptime(paste(d$Date,d$Time,sep=" "), "%Y-%m-%d %H:%M:%S")
par(mfcol = c(2,2))
plot(d[[2]],d[[3]],type="n",xlab="",ylab="Global Active Power (kilowatts)")
lines(d[[2]],d[[3]])
plot(d[[2]],d[[7]],type="n",xlab="",ylab="Energy sub metering")
lines(d[[2]],d[[7]],col="black")
lines(d[[2]],d[[8]],col="red")
lines(d[[2]],d[[9]],col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
plot(d[[2]],d[[5]],type="n",xlab="datetime",ylab="Voltage")
lines(d[[2]],d[[5]])
plot(d[[2]],d[[4]],type="n",xlab="datetime",ylab="Global_reactive_power")
lines(d[[2]],d[[4]])
dev.off()